### ISSUE TITLE
Sync/Async

### ISSUE THREAD

**Issue by m-bock** [purescript-node/purescript-node-child-process#22]
Is there a reason why this library does only has bindings to the async versions of the functions? `spawnSync` e.g. is missing. `purescript-node-fs` has split them into a `Sync` and `Async` module, maybe an option for this one too?

**Comment by garyb** [comment]
I think it's just that the `Sync` versions didn't exist when this library was created, and nobody has thought to add them since. 🙂

**Comment by JordanMartinez** [comment]
These have been implemented in #46
