### ISSUE TITLE
Can we use this with esbuild

### ISSUE THREAD

**Issue by Kali95739** [purescript-node/purescript-node-child-process#38]
Want to know the best way to use this in the browser I heard recently all of purescript changed to es6 fully did this as well?

**Comment by garyb** [comment]
You can't use this library in the browser as it's for the build in `child-process` module provided by the `node` runtime.

Are you perhaps looking for something based on web workers if you're in the browser?

**Comment by Kali95739** [comment]
So we cant use the FS module as well in purescript?

**Comment by Kali95739** [comment]
It should be possible to bundle it in such a way that we can transpile a
function into a web worker or such yes but Im looking for something based
on es6 or a alternative I have found a few but I was wondering if this one
actually would transpile through purescript and esbuild but thank you

**Comment by JordanMartinez** [comment]
Closing as this was a question that seems to have been mostly answered.
